"""Real ngspice ``.lib`` PVT-corner (``.LIB ... .ENDL``) editing --
parsing with real line-number tracking, write-back
(``pdklib/spice_models_writer.py``), the real quoted-formula-param
quoting fix, and the real, driven ``gui/spice_models_view.py`` Corners
editor end to end (New/Delete Corner, rename, param/include edits,
save + reload persistence, real export). Corners were read-only until
this feature -- direct user feedback ("they should be [editable]")."""

import sys
sys.path.insert(0, "/foss/designs")
import tempfile
import tkinter as tk
from pathlib import Path

from openpdkcreator import export as export_mod
from openpdkcreator import project_io
from openpdkcreator.gui.app import App
from openpdkcreator.pdklib import spice_models as spice_mod
from openpdkcreator.pdklib import spice_models_writer as writer_mod

PDK_ROOT = Path("/foss/designs/data/ihp-sg13g2/ihp-sg13g2")

# --- 1. Real parser + writer: byte-identical no-edit export across
#     every real IHP .lib file, and a real edit round trip (param
#     edit, new corner, deleted corner) ---
lib_files = spice_mod.find_lib_files(PDK_ROOT)
assert lib_files, "no real .lib files found"

total_corners = mismatches = 0
for f in lib_files:
    lib = spice_mod.parse_lib_file(f)
    total_corners += len(lib.corners)
    if writer_mod.render_lib_file(f, lib) != f.read_text(encoding="utf-8", errors="replace"):
        mismatches += 1
        print("MISMATCH (no edit):", f)
print(f"real .lib files: {len(lib_files)}, real corners parsed: {total_corners}")
assert total_corners == 47  # confirmed real, see pdklib/spice_models.py's own docstring
assert mismatches == 0
print("PASS: no-edit export byte-identical across every real IHP .lib file.")

target = next(f for f in lib_files if spice_mod.parse_lib_file(f).corners)
lib = spice_mod.parse_lib_file(target)
orig_corner = lib.corners[0]
orig_corner.params = list(orig_corner.params) + [("zzz_test", "1.23")]
new_corner = spice_mod.SpiceCorner(name="ZZZ_NEW_CORNER", params=[("foo", "bar")], includes=["some_file.lib"])
lib.corners.append(new_corner)
deleted_name = lib.corners[1].name if len(lib.corners) > 2 else None
if deleted_name:
    del lib.corners[1]

rendered = writer_mod.render_lib_file(target, lib)
assert "zzz_test = 1.23" in rendered
assert ".LIB ZZZ_NEW_CORNER" in rendered and ".ENDL ZZZ_NEW_CORNER" in rendered and "foo = bar" in rendered

tmp_path = Path(tempfile.mktemp(suffix=".lib"))
tmp_path.write_text(rendered)
try:
    lib2 = spice_mod.parse_lib_file(tmp_path)
    reloaded_first = lib2.corners[0]
    assert reloaded_first.name == orig_corner.name
    assert dict(reloaded_first.params)["zzz_test"] == "1.23"
    assert any(c.name == "ZZZ_NEW_CORNER" and dict(c.params).get("foo") == "bar" for c in lib2.corners)
    if deleted_name:
        assert not any(c.name == deleted_name for c in lib2.corners)
finally:
    tmp_path.unlink()
print("PASS: real edit round trip (param edit, new corner, deleted corner) survives render + re-parse.")

# --- 2. A real, quoted formula-valued param (confirmed real elsewhere
#     in this deck, e.g. capacitors_mod_mismatch.lib's own
#     cap_carea_mm='agauss(...)') keeps its own real quoting when its
#     corner block is regenerated by an unrelated edit ---
content = (
    "* synthetic corner file for a real formula-param round-trip check\n"
    ".LIB TT\n"
    ".param plain = 100\n"
    ".param cap_carea_mm = 'agauss(1, 0.01, (mm_ok != 1 ? 0 : 1))'\n"
    ".ENDL TT\n"
)
tmp_path = Path(tempfile.mktemp(suffix=".lib"))
tmp_path.write_text(content)
try:
    lib3 = spice_mod.parse_lib_file(tmp_path)
    corner3 = lib3.corners[0]
    assert dict(corner3.params)["cap_carea_mm"] == "agauss(1, 0.01, (mm_ok != 1 ? 0 : 1))"
    assert writer_mod.render_lib_file(tmp_path, lib3) == content

    corner3.params = [(k, ("999" if k == "plain" else v)) for k, v in corner3.params]
    rendered3 = writer_mod.render_lib_file(tmp_path, lib3)
    assert "cap_carea_mm = 'agauss(1, 0.01, (mm_ok != 1 ? 0 : 1))'" in rendered3, "formula param lost its quoting"

    tmp2 = Path(tempfile.mktemp(suffix=".lib"))
    tmp2.write_text(rendered3)
    try:
        lib4 = spice_mod.parse_lib_file(tmp2)
        assert dict(lib4.corners[0].params)["cap_carea_mm"] == "agauss(1, 0.01, (mm_ok != 1 ? 0 : 1))"
        assert dict(lib4.corners[0].params)["plain"] == "999"
    finally:
        tmp2.unlink()
finally:
    tmp_path.unlink()
print("PASS: a quoted, formula-valued param round-trips correctly through an edit that regenerates its own block.")

# --- 3. The real, driven gui/spice_models_view.py Corners editor:
#     rename, param/include edits, New/Delete Corner, save + reload
#     persistence (fresh App instance), and real export ---
save_path = project_io.save_path_for(PDK_ROOT)
if save_path.is_file():
    save_path.unlink()

root = tk.Tk()
app = App(root, PDK_ROOT)
root.update()

smv = app.spice_models_view
target_name = next(
    name for name, path in smv.lib_files.items() if spice_mod.parse_lib_file(path).corners
)
smv.file_var.set(target_name)
smv._refresh_all()
root.update()
before_count = len(smv.current.corners)

first_iid = smv.corners_tree.get_children()[0]
smv.corners_tree.selection_set(first_iid)
smv._on_corner_select()
root.update()
smv.corner_name_var.set("RENAMED_CORNER")
smv.corner_params_text.delete("1.0", "end")
smv.corner_params_text.insert("1.0", "gui_test_param = 42\nanother = xyz")
smv.corner_params_text.event_generate("<<Modified>>")
root.update()
assert smv.current_corner.name == "RENAMED_CORNER"
assert dict(smv.current_corner.params)["gui_test_param"] == "42"

smv._new_corner()
root.update()
assert len(smv.current.corners) == before_count + 1
new_corner = smv.current.corners[-1]
smv.corner_name_var.set("GUI_NEW_CORNER")
smv.corner_params_text.delete("1.0", "end")
smv.corner_params_text.insert("1.0", "foo = bar")
smv.corner_params_text.event_generate("<<Modified>>")
smv.corner_includes_text.insert("1.0", "some_other_file.lib")
smv.corner_includes_text.event_generate("<<Modified>>")
root.update()
assert new_corner.name == "GUI_NEW_CORNER"
assert dict(new_corner.params)["foo"] == "bar"
assert new_corner.includes == ["some_other_file.lib"]
print("PASS: real corner form (rename/params/includes) and New Corner both commit to the real, live SpiceCorner.")

app._save_project()
root.update()
root.destroy()

root2 = tk.Tk()
app2 = App(root2, PDK_ROOT)
root2.update()
smv2 = app2.spice_models_view
smv2.file_var.set(target_name)
smv2._refresh_all()
root2.update()

names2 = [c.name for c in smv2.current.corners]
assert "RENAMED_CORNER" in names2 and "GUI_NEW_CORNER" in names2
renamed2 = next(c for c in smv2.current.corners if c.name == "RENAMED_CORNER")
assert dict(renamed2.params)["gui_test_param"] == "42"
new2 = next(c for c in smv2.current.corners if c.name == "GUI_NEW_CORNER")
assert dict(new2.params)["foo"] == "bar" and new2.includes == ["some_other_file.lib"]
print("PASS: renamed + brand-new corners both survive a real save + fresh-process App reload.")

smv2.corners_tree.selection_set(str(id(new2)))
smv2._on_corner_select()
root2.update()
smv2._delete_corner()
root2.update()
assert not any(c.name == "GUI_NEW_CORNER" for c in smv2.current.corners)
print("PASS: Delete Corner removes the real, selected SpiceCorner.")

with tempfile.TemporaryDirectory() as tmp:
    written = export_mod.export_spice_lib_files(PDK_ROOT, smv2.lib_cache, dest_root=Path(tmp))
    target_export = [p for p in written if p.name == Path(target_name).name][0]
    text = target_export.read_text()
    assert ".LIB RENAMED_CORNER" in text and "gui_test_param = 42" in text and "GUI_NEW_CORNER" not in text
print("PASS: real Export Edited SPICE .lib Corners reflects rename + param edit + delete correctly.")

root2.destroy()
if save_path.is_file():
    save_path.unlink()

print("ALL SPICE CORNER TESTS PASS")
