import sys
sys.path.insert(0, "/foss/designs")
import tkinter as tk
from pathlib import Path
import shutil

from openpdkcreator.gui.app import App
from openpdkcreator import export as export_mod
from openpdkcreator.ihp import library_index as li_mod
from openpdkcreator.ihp import libman_project as libman_mod
from openpdkcreator.gui import library_manager_view as lmv_mod

PDK_ROOT = Path("/foss/designs/data/ihp-sg13g2/ihp-sg13g2")
PROJECT_ROOT = export_mod.PROJECT_ROOT
TMP = Path("/tmp/test_libman_project_gui")

registry_path = li_mod.registry_path(PROJECT_ROOT)
registry_path.unlink(missing_ok=True)
shutil.rmtree(PROJECT_ROOT / lmv_mod.LIBRARIES_DIRNAME, ignore_errors=True)
shutil.rmtree(TMP, ignore_errors=True)
TMP.mkdir(parents=True)

root = tk.Tk()
app = App(root, PDK_ROOT)
root.update()

lmv = app.library_manager_view

# --- Export: writes a real .projects file with one real define() per
# real, LibMan-understood view kind (GDS/Xschem/Qucs), skipping every
# other real kind (LEF/CDL/SPICE/Verilog/Liberty/Magic Layout) ---
export_path = TMP / "exported.projects"
original_asksaveasfilename = lmv_mod.filedialog.asksaveasfilename
lmv_mod.filedialog.asksaveasfilename = lambda *a, **kw: str(export_path)
try:
    lmv._export_libman_project()
finally:
    lmv_mod.filedialog.asksaveasfilename = original_asksaveasfilename
assert export_path.is_file()
exported_text = export_path.read_text()
assert exported_text.startswith("# KLayout library definition file\n")
reparsed = libman_mod.parse_project_file(export_path)
assert len(reparsed.defines) > 0

real_exportable_count = 0
for library, _is_real in li_mod.merged_libraries(PDK_ROOT, PROJECT_ROOT):
    for (_cell, view_kind), _entry in li_mod.merged_entries(PDK_ROOT, PROJECT_ROOT, library).items():
        if view_kind in lmv._LIBMAN_EXPORTABLE_KINDS:
            real_exportable_count += 1
assert len(reparsed.defines) == real_exportable_count, (len(reparsed.defines), real_exportable_count)
assert any(d.name == "sg13g2_stdcell" and d.path.endswith(".gds") for d in reparsed.defines)
print(f"PASS: Export writes a real, re-parseable .projects file with exactly the {real_exportable_count} real, LibMan-understood views.")

# --- Import: a real, hand-authored .projects file pointing at real
# files this project already has, plus the real, honest edge cases
# (a nonexistent path, a bare non-file reference, an opaque LibMan
# CORE-format file this app can't open) ---
real_gds = next(PDK_ROOT.glob("libs.ref/sg13g2_io/gds/*.gds"))
real_sym = next((PDK_ROOT / "libs.tech" / "xschem").rglob("*.sym"))

opaque_dir = TMP / "opaque_lib" / "some_cell"
opaque_dir.mkdir(parents=True)
opaque_core_file = opaque_dir / "some_cell.layout.core"
opaque_core_file.write_bytes(b"\x00\x01real-binary-capnp-stream-not-actually-parseable")

import_fixture = TMP / "import_test.projects"
import_fixture.write_text(
    "# KLayout library definition file\n"
    "# Generated by LibMan\n\n"
    f'define("test_import_lib", "{real_gds}");\n'
    f'define("test_import_lib", "{real_sym}");\n'
    f'define("test_import_lib", "{opaque_core_file}");\n'
    'define("test_import_lib", "/no/such/real/file/anywhere.gds");\n'
    'define("analogLib", "analogLib");\n'
)

original_askopenfilename = lmv_mod.filedialog.askopenfilename
lmv_mod.filedialog.askopenfilename = lambda *a, **kw: str(import_fixture)
try:
    lmv._import_libman_project()
finally:
    lmv_mod.filedialog.askopenfilename = original_askopenfilename
root.update()

print("status after import:", lmv.status_var.get())
assert "3 real, viewable" not in lmv.status_var.get()  # 1 gds + 1 sym = 2 real viewable, 1 opaque
assert "2 real, viewable view(s) + 1 real LibMan" in lmv.status_var.get(), lmv.status_var.get()
assert "2 real define(s) skipped" in lmv.status_var.get(), lmv.status_var.get()

entries = li_mod.merged_entries(PDK_ROOT, PROJECT_ROOT, "test_import_lib")
gds_entries = [e for (_c, k), e in entries.items() if k == "gds"]
sym_entries = [e for (_c, k), e in entries.items() if k == "xschem_symbol"]
core_entries = [e for (_c, k), e in entries.items() if k == "libman_core"]
assert len(gds_entries) == 1 and gds_entries[0].path == real_gds
assert len(sym_entries) == 1 and sym_entries[0].path == real_sym
assert len(core_entries) == 1 and core_entries[0].path == opaque_core_file
print("PASS: Import registers real, viewable views under their correct, real view kind, and tracks the real, opaque LibMan CORE file honestly.")

# --- The Views pane shows no "View" button for a libman_core entry --
# an honest label instead, not a misleading generic text-preview ---
lmv.library_tree.selection_set("test_import_lib")
root.update()
core_cell = core_entries[0].cell
lmv.cell_tree.selection_set(core_cell)
root.update()
assert "libman_core" in lmv._entries
row_frame = lmv.views_rows_frame.winfo_children()[list(li_mod.VIEW_KIND_ORDER).index("libman_core")]
row_widget_texts = [w.cget("text") for w in row_frame.winfo_children() if "text" in w.keys()]
assert any("LibMan's own format" in t for t in row_widget_texts), row_widget_texts
assert not any(t.startswith("View") for t in row_widget_texts)
print("PASS: the libman_core row shows an honest label, never a misleading generic View button.")

# --- A real syntax error in the imported file reports an honest error
# dialog, not a silent partial import ---
bad_fixture = TMP / "bad.projects"
bad_fixture.write_text('define("no closing paren";\n')
lmv_mod.filedialog.askopenfilename = lambda *a, **kw: str(bad_fixture)
original_showerror = lmv_mod.messagebox.showerror
errors_shown = []
lmv_mod.messagebox.showerror = lambda title, message, **kw: errors_shown.append((title, message))
try:
    lmv._import_libman_project()
finally:
    lmv_mod.filedialog.askopenfilename = original_askopenfilename
    lmv_mod.messagebox.showerror = original_showerror
assert len(errors_shown) == 1
assert "bad.projects:1" in errors_shown[0][1]
print("PASS: a real syntax error in the imported file surfaces an honest error dialog, not a silent partial import.")

root.destroy()
registry_path.unlink(missing_ok=True)
shutil.rmtree(PROJECT_ROOT / lmv_mod.LIBRARIES_DIRNAME, ignore_errors=True)
shutil.rmtree(TMP, ignore_errors=True)
print("ALL LIBMAN PROJECT GUI TESTS PASS")
