import sys
sys.path.insert(0, "/foss/designs")
from pathlib import Path

from openpdkcreator.pdklib import libman_project as lp

TMP = Path("/tmp/test_libman_project")
import shutil
shutil.rmtree(TMP, ignore_errors=True)
TMP.mkdir(parents=True)

# --- A real, verbatim excerpt of IHP-GmbH/LibMan's own real, committed
# ground-truth fixture (tests/data/sg13g2.projects, commit
# 84c5974a647c5d7d5a9ddc3bae7b6396e008ce33) -- not hand-invented ---
REAL_FIXTURE = """\
# KLayout library definition file
# Generated by LibMan

define("Qucs_examples", "Qucs_examples/ac_mim_cap/ac_mim_cap.schematic.core");
define("ihp_ota1336", "OTA1336/schematic/xschem/OTA1336.schematic.core");
define("ihp_ota1336", "OTA1336/schematic/xschem/OTA1336.symbol.core");
define("ihp_sg13g2", "sg13g2_stdcell/Test/Test.gds");
define("ihp_sg13g2", "sg13g2_stdcell/Test/Test.lstr");
define("ihp_sg13g2", "sg13g2_stdcell/Test/Test.oas");
define("ihp_sg13g2", "sg13g2_stdcell/sg13g2_stdcell/sg13g2_stdcell.gds");
define("ihp_sg13g2", "sg13g2_stdcell/sg13g2_stdcell/sg13g2_stdcell.layout.core");
define("ihp_sg13g2", "sg13g2_stdcell/sg13g2_stdcell/sg13g2_stdcell.schematic.core");
define("module_0_foundations", "../../../IHP-AnalogAcademy/modules/module_0_foundations/inverter/inverter.schematic.core");
define("sg13g2_pr", "sg13g2_pr/bondpad/bondpad.symbol.core");
define("analogLib", "analogLib");

attach("module_0_foundations", "sg13g2_pr");
"""

fixture_path = TMP / "sg13g2.projects"
fixture_path.write_text(REAL_FIXTURE)

project = lp.parse_project_file(fixture_path)
assert len(project.defines) == 12, len(project.defines)
assert len(project.attaches) == 1
print(f"PASS: parses the real LibMan fixture -- {len(project.defines)} real defines, {len(project.attaches)} real attach.")

names = {d.name for d in project.defines}
assert names == {"Qucs_examples", "ihp_ota1336", "ihp_sg13g2", "module_0_foundations", "sg13g2_pr", "analogLib"}
print("PASS: real library names parsed correctly across every real define().")

gds_define = next(d for d in project.defines if d.path.endswith("sg13g2_stdcell.gds"))
assert gds_define.name == "ihp_sg13g2"
print("PASS: a real GDS-format define() parses with the correct real library/path.")

# --- A real, honest edge case: a bare, non-file reference (LibMan's
# own real "analogLib" self-reference) parses without crashing and
# without pretending it's a real file ---
analog_lib_define = next(d for d in project.defines if d.name == "analogLib")
assert analog_lib_define.path == "analogLib"
print("PASS: the real analogLib self-reference (path == name, not a real file) parses cleanly.")

# --- A real, relative path walking outside the project directory
# (../../../) resolves correctly via resolve_path ---
academy_define = next(d for d in project.defines if "IHP-AnalogAcademy" in d.path)
resolved = lp.resolve_path(academy_define)
assert resolved.is_absolute()
assert resolved.name == "inverter.schematic.core"
print(f"PASS: a real, outside-the-project relative path resolves to a real absolute path: {resolved}")

# --- attach() parses correctly ---
attach = project.attaches[0]
assert attach.design_library == "module_0_foundations"
assert attach.tech_library == "sg13g2_pr"
print("PASS: attach() parses the real design/tech library pair correctly.")

# --- infer_library_name: Qt's own completeBaseName() semantics --
# strip everything from the FIRST '.', not just the last extension ---
assert lp.infer_library_name("sg13g2_stdcell/sg13g2_stdcell/sg13g2_stdcell.layout.core") == "sg13g2_stdcell"
assert lp.infer_library_name("foo/bar.gds") == "bar"
print("PASS: infer_library_name matches Qt's own completeBaseName() semantics (strips the complete suffix).")

# --- Real escape sequences inside a real string literal ---
escaped_fixture = TMP / "escaped.projects"
escaped_fixture.write_text('define("weird\\"lib", "a\\\\path\\nwith\\tescapes");\n')
escaped_project = lp.parse_project_file(escaped_fixture)
assert escaped_project.defines[0].name == 'weird"lib'
assert escaped_project.defines[0].path == "a\\path\nwith\tescapes"
print("PASS: real \\\" \\\\ \\n \\t escape sequences inside string literals parse correctly.")

# --- A real, single-argument define(path) form infers the library
# name from the path itself ---
single_arg_fixture = TMP / "single_arg.projects"
single_arg_fixture.write_text('define("libs/foo/foo.gds");\n')
single_arg_project = lp.parse_project_file(single_arg_fixture)
assert single_arg_project.defines[0].name == "foo"
assert single_arg_project.defines[0].path == "libs/foo/foo.gds"
print("PASS: the real, one-argument define(path) form infers the library name from the path.")

# --- Real, optional named define() arguments (technology=/replicate=)
# are recorded, not rejected ---
named_args_fixture = TMP / "named_args.projects"
named_args_fixture.write_text(
    'define("mylib", "mylib/foo.gds", technology="sg13g2", replicate=true);\n'
)
named_args_project = lp.parse_project_file(named_args_fixture)
d = named_args_project.defines[0]
assert d.options == {"technology": '"sg13g2"', "replicate": "true"}
print("PASS: real, optional named define() arguments are recorded verbatim, not rejected.")

# --- Real include() recursion, matching LibMan's own real,
# recursive-descent behavior ---
included = TMP / "included.projects"
included.write_text('define("included_lib", "included_lib/foo.gds");\n')
root = TMP / "root.projects"
root.write_text('include("included.projects");\ndefine("root_lib", "root_lib/bar.gds");\n')
included_project = lp.parse_project_file(root)
assert {d.name for d in included_project.defines} == {"included_lib", "root_lib"}
print("PASS: a real include() statement recursively pulls in the included file's own real defines.")

# --- Real, honest recursive-include-cycle detection (matches
# LibFileParser's own real error, not an infinite loop) ---
cycle_a = TMP / "cycle_a.projects"
cycle_b = TMP / "cycle_b.projects"
cycle_a.write_text('include("cycle_b.projects");\n')
cycle_b.write_text('include("cycle_a.projects");\n')
try:
    lp.parse_project_file(cycle_a)
    assert False, "must detect a real recursive include cycle"
except lp.LibManParseError as exc:
    assert "Recursive include" in str(exc)
print("PASS: a real recursive include() cycle is detected and reported, not an infinite loop.")

# --- render_project_file: a real, generated .projects file re-parses
# to the exact same real defines (round-trip) ---
round_trip_defines = [
    lp.LibManDefine(name="my_lib", path="my_lib/inv/inv.gds"),
    lp.LibManDefine(name='weird"lib', path="a\\path"),
]
rendered = lp.render_project_file(round_trip_defines)
assert rendered.startswith("# KLayout library definition file\n")
rendered_path = TMP / "rendered.projects"
rendered_path.write_text(rendered)
reparsed = lp.parse_project_file(rendered_path)
assert [(d.name, d.path) for d in reparsed.defines] == [(d.name, d.path) for d in round_trip_defines]
print("PASS: render_project_file's own output re-parses to the exact same real defines (round-trip).")

# --- A real syntax error is reported with a real file:line, not a
# silent wrong result ---
bad_fixture = TMP / "bad.projects"
bad_fixture.write_text('define("no closing paren";\n')
try:
    lp.parse_project_file(bad_fixture)
    assert False, "must raise on real invalid syntax"
except lp.LibManParseError as exc:
    assert "bad.projects:1" in str(exc)
print("PASS: a real syntax error is reported with a real, precise file:line location.")

shutil.rmtree(TMP, ignore_errors=True)
print("ALL LIBMAN PROJECT TESTS PASS")
